name: Check comment and deploy when requested

on:
  issue_comment:
    types:
      - created

jobs:
  get-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    outputs:
      SB_NAME: ${{ env.SB_NAME }}
      IS_UNAFFECTED: ${{ env.IS_UNAFFECTED }}
    steps:          
#      - name: Get PR
#        run: |
#            RESPONSE=$(curl --request GET \
#            --url "${{github.event.issue.pull_request.url}}" \
#            --header 'Accept: application/vnd.github.v3+json' 2>/dev/null)            
#            echo "BRANCH_NAME=$(echo $RESPONSE | jq -r '.head.ref')" >> $GITHUB_ENV
            
      - name: print 1
        run: |
          echo $BRANCH_NAME
        
      - name: valid empty branch
        if: ${{ !env.BRANCH_NAME }}
        run: |
          echo '${{toJSON(env.JSON) }}'
      
      - name: is empty branch
        if: ${{ env.BRANCH_NAME == ''}}
        run: |
          echo 'IS EMPTY BRANCH'
          
      - name: run JS script
        id: run_script
        uses: actions/github-script@v6
        env:
          COMMAND: ${{ github.event.comment.body }}
        with:
          script: |
            const cmd = process.env.COMMAND?.toString().toLowerCase() || ""
            console.log(`Command found ${cmd}`)

            if (cmd.toString().startsWith("build storybook ")){
                const c = cmd.split(" ")
                if(c[2]){
                    core.exportVariable('SB_NAME', c[2]);      
                }

            }

            core.exportVariable('IS_UNAFFECTED', cmd.toString().startsWith("build unaffected"));    

      - name: print ENVS
        run: |
          echo ${{ env.SB_NAME}}
          echo ${{ env.IS_UNAFFECTED}}
  
  build-single-sb:
    runs-on: ubuntu-latest
    needs: get-comment
    if: ${{ needs.get-comment.outputs.SB_NAME != '' && needs.get-comment.outputs.SB_NAME != 'affected'}}
    steps:
      - run: echo ${{ needs.get-comment.outputs.SB_NAME }}

  build-affected-sb:
    runs-on: ubuntu-latest
    needs: get-comment
    if: ${{ needs.get-comment.outputs.SB_NAME == 'affected'}}
    steps:
      - run: echo ${{ needs.get-comment.outputs.SB_NAME }}

  build-unaffected:
    runs-on: ubuntu-latest
    needs: get-comment
    if: ${{ needs.get-comment.outputs.IS_UNAFFECTED == 'true' }}
    steps:
      - run: echo ${{ needs.get-comment.outputs.IS_UNAFFECTED }}
