name: Check comment and deploy when requested

on:
  issue_comment:
    types:
      - created

jobs:
  get-comments:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Comment
        run: |
          echo ${{ github.event.comment.body }}

      - name: Comment github
        run: |
          echo TST
          
        #${{ toJSON(github) }}
          
      - name: Get PR
        run: |
            RESPONSE=$(curl --request GET \
              --url "${{github.event.issue.pull_request.url}}" \
              --header 'Accept: application/vnd.github.v3+json' 2>/dev/null)
            echo '${{toJSON(RESPONSE).head.ref }}'
          
