name: Check comment and deploy when requested

on:
  issue_comment:
    types:
      - created

jobs:
  get-comments:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Comment
        run: |
          echo ${{ github.event.comment.body }}

      - name: Comment github
        run: |
          echo ${{ toJSON(github) }}
