name: Check comment and deploy when requested

on:
  issue_comment:
    types:
      - created

jobs:
  get-comments:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    steps:
      - name: Comment
        run: |
          echo ${{ github.event.comment.body }}

      - name: Comment github
        run: |
          echo ${{ toJSON(github) }}
          
      - name: Get PR
        run: |
          gh api --header 'Accept: application/vnd.github+json' --method GET ${{ github.event.issue.pull_request.url }} > data.json
          
      - name: print json
        run: |
          echo ${{ toJSON(data.json) }}
