name: 'ACTION GENERIC deploy'
  
on:
  workflow_call:
    inputs:
      affected-apps:
        required: true
        type: string
jobs:
  deploy:
    runs-on: ubuntu-latest    
    steps:
      - uses: jungwinter/split@v2
        id: split
        with:
          msg: ${{ inputs.affected-apps }}
          separator: ","