name: Deploy
on:
  push:
    branches: [develop]
env:
  BEFORE_SHA: '${{ github.event.before }}'
jobs:
  install-dependecy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Use Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16

      #- run: git fetch origin develop

      - name: Install yarn
        run: npm install yarn --location=global

      - name: Install packages
        run: yarn install

      - name: Cache yarn dependencies
        uses: actions/cache@v3
        id: yarn-cache
        with:
          path: |
            ${{ steps.yarn-cache-dir-path.outputs.dir }}
            **\node_modules
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-
      - name: Install dependencies
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install

      - name: Run Affected Test-Release         
        #run: yarn affected:test
        run: yarn affected:test --base=develop  

      - name: 'Get affected apps'
        id: affected-apps
        run: echo '::set-output name=apps::$(yarn affected-apps --base=develop)'
          #echo "AFFECTED_APP=$(yarn affected-apps --base=develop)" >> $GITHUB_ENV

      - name: 'Print CENTAURO'
        #if: ${{ contains(env.AFFECTED_APPS, 'centauro-bff') }}
        if: ${{ contains(steps.affected-apps.outputs.apps, 'centauro-bff') }}
        run: echo CENTAUROOOOOO

      - name: 'Print NIKE'
        if: ${{ contains(steps.affected-apps.outputs.apps, 'nike-bff') }}
        run: echo NIKEEEEEEE       