name: Nx Affected Test
on:
  push:
    branches: [master]
env:
  BEFORE_SHA: '${{ github.event.before }}'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Use Node.js 16.x
        uses: actions/setup-node@v2
        with:
          node-version: 16.x
      #- run: git fetch origin master
      - name: Install packages
        run: npm install
      #  
      #- name: Run Affected Test-Release 
      #  shell: bash
      #  run: npm run affected:test
      #  run: npm run affected:test -- --base=$BEFORE_SHA

      - name: 'Get affected apps'
        run: |
          echo ::set-env name=AFFECTED_APPS::$(npm run affected-apps)

      - name: 'Print CENTAURO'
        if: ${{ contains(env.AFFECTED_APPS, 'centauro-bff') }}
        run: echo CENTAUROOOOO

      - name: 'Print NIKE'
        if: ${{ contains(env.AFFECTED_APPS, 'nike-bff') }}
        run: echo NIKEEEEEEE